version: '2'

services:
  idrac1:
    image: mikolatero/idrac5
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=idrac1.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
    volumes:
      - /opt/isos:/isos
  idrac2:
    image: mikolatero/idrac5
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    environment:
      - IDRAC_HOST=idrac2.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
    volumes:
      - /opt/isos:/isos